@echo off
cd /d "%~dp0"
echo [1/3] Creating virtual environment (if missing)...
if not exist ".venv" (
    python -m venv .venv
)
echo [2/3] Activating virtual environment...
call .venv\Scripts\activate
echo [3/3] Installing requirements...
pip install -r requirements.txt
echo Starting BoardMeeting on http://localhost:8000 ...
uvicorn app:app --host 0.0.0.0 --port 8000 --reload
